export const IT_CATEGORY = [
    "Thiết kế Web",
    "Phát triển ứng dụng di động",
    "Phát triển Frontend",
    "Phát triển Backend",
    "Phát triển Fullstack",
    "Thiết kế UI/UX",
    "Phát triển Game",
    "Trí tuệ nhân tạo (AI)",
    "Học máy (Machine Learning)",
    "Khoa học dữ liệu",
    "Dữ liệu lớn (Big Data)",
    "Điện toán đám mây",
    "DevOps",
    "An ninh mạng",
    "Công nghệ Blockchain",
    "Internet vạn vật (IoT)",
    "Thực tế tăng cường (AR)",
    "Thực tế ảo (VR)",
    "Kiểm thử phần mềm",
    "Đảm bảo chất lượng (QA)",
    "Quản trị mạng",
    "Quản trị hệ thống",
    "Quản trị cơ sở dữ liệu",
    "Phát triển cơ sở dữ liệu",
    "Hỗ trợ kỹ thuật (IT Support)",
    "Viết tài liệu kỹ thuật",
    "Phát triển phần mềm nhúng",
    "Phát triển ứng dụng doanh nghiệp",
    "Tự động hóa quy trình bằng RPA",
    "Phân tích kinh doanh (Business Analysis)",
    "Phân tích hệ thống",
    "Lập trình nhúng",
    "Phát triển trí tuệ nhân tạo (AI Development)",
    "Phát triển ứng dụng thực tế ảo (VR App Development)",
    "Phát triển ứng dụng thực tế tăng cường (AR App Development)",
    "Phân tích dữ liệu",
    "Quản lý dự án công nghệ (IT Project Management)",
    "Hỗ trợ vận hành IT",
    "Kỹ thuật mạng máy tính",
    "Phát triển ứng dụng web",
    "Phát triển ứng dụng desktop",
    "Quản trị sản phẩm kỹ thuật số",
    "Thiết kế trò chơi",
    "Phát triển công cụ tự động hóa",
    "Quản lý vận hành hệ thống (SysOps)",
    "Học sâu (Deep Learning)",
    "Phát triển chatbot",
    "Tư vấn công nghệ thông tin",
    "Tích hợp hệ thống",
    "Phân phối nội dung (CDN Management)"
  ];
  