export const LANGUAGE = [
  "Tiếng Anh",
  "Tiếng Trung (Mandarin)",
  "Tiếng Tây Ban Nha",
  "Tiếng Hindi",
  "Tiếng Ả Rập",
  "Tiếng Pháp",
  "Tiếng Nga",
  "Tiếng Bồ Đào Nha",
  "Tiếng Bengali",
  "Tiếng Urdu",
  "Tiếng Indonesia",
  "Tiếng Nhật",
  "Tiếng Đức",
  "Tiếng Punjabi",
  "Tiếng Tamil",
  "Tiếng Telugu",
  "Tiếng Thái",
  "Tiếng Việt",
  "Tiếng Hàn",
  "Tiếng Filipino (Tagalog)",
  "Tiếng Malay",
  "Tiếng Farsi (Persian)",
  "Tiếng Ukraina",
  "Tiếng HHebrew",
  "Tiếng Swahili",
];
